config/routes.rb
SisconOtica::Application.routes.draw do

  resources :nomes

  resources :vendas 
  resources :clientes

  resources :tipo_funcionarios

  devise_for :funcionarios,  :controllers => { :registrations => "funcionarios/registrations" }
  resources :tipo_produtos

  resources :produtos
  get '/cadastrar' => 'welcome#cadastrar'
  get '/consultar' => 'welcome#consultar'
  get '/relatorios' => 'welcome#relatorios'
  get '/funcionarios' => 'welcome#listafuncionarios'
  root 'welcome#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
    validates :email, :nome, :cpf,
	presence: true
	validates :email, :cpf, uniqueness: true
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_funcionario!
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cliente }
      else
        format.html { render action: 'new' }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :endereco, :foneResidencial, :FoneCelular, :Cpf, :FotoCliente, :email, :DataNascimento, :bairro, :cidade, :cep, :estado)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= simple_form_for(@cliente ,:html => { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="span4">
     <%= f.input :nome, label: "Nome Completo: ", required: true, autofocus: true %>
     </div>
     <div class="span4" style="margin-left: 80px;">
    <%= f.input :cpf, label: "CPF", required: true, input_html: {id: 'cpf'}%>
    </div>
        <div class="span9">
    <%= f.input :dataNascimento, label: "Data Nascimento" %>
    </div>
    <div class="span4">
    <%= f.input :email, label: "Email", required: true  %>
    </div>

    <div class="span4"  style="margin-left: 80px;">
    <%= f.input :foneResidencial, label: "Telefone Residencial", input_html: { class: 'telefone'}%>
    </div>
    <div class="span4" >
    <%= f.input :foneCelular, label: "Telefone Celular" , input_html: { class: 'telefone'}%>
    </div>
    <div class="span4" style="margin-left: 80px;">
    <%= f.input :endereco, label: "Endereço" %>
    </div>
    <div class="span4" >
    <%= f.input :bairro, label: "Bairro"%>
    </div>
    <div class="span4"  style="margin-left: 80px;">
    <%= f.input :estado, :label => "Estado", :collection => ["AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN","RS","RO","RR,","SC","SP","SE","TO"], :selected => "Escolha" %>
    </div>
    <div class="span4" >
    <%= f.input :cidade, label: "Cidade"%>
    </div>
    <div class="span4"  style="margin-left: 80px;">
    <%= f.input :cep, label: "CEP", input_html: {id: 'cep'}%>
    </div>
    <div class="span9">
    <%= f.button :submit, "Registrar"%>
    </div>

  </div>
    
    <% end %>

app/views/clientes/edit.html.erb
<br>
<h2>Editando cliente</h1>
<br>
<%= render 'form' %>

<%= link_to 'Mostrar', @cliente, class: "relatoriogerar" %> |
<%= link_to 'Voltar', clientes_path, class: "relatoriogerar" %>

app/views/clientes/index.html.erb
<br>
<h2>Listando Clientes</h2>
<br>

<table class="table table-hover table-bordered" style="background: #ffffff">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Telefone Celular</th>
      <th>CPF</th>
      <th>Email</th>
      <th>Cidade</th>
      <th colspan=3>Ações</th>

    </tr>
  </thead>
  

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.foneCelular %></td>
        <td><%= cliente.cpf %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.cidade %></td>
        <td><%= link_to 'Mostrar', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <%if current_funcionario.tipo == "Administrador"%>
        <td>
        <%= link_to 'Apagar', cliente, method: :delete, data: { confirm: 'Tem certeza que deseja apagar?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path, class: "relatoriogerar" %>

app/views/clientes/new.html.erb
<ol class="breadcrumb" style="margin-left: -15px;">
  <li><a href="<%= root_path %>">Inicio</a> /  </li>
  <li><a href="<%= cadastrar_path %>">Cadastrar</a> / </li>
  <li class="active">Cliente</li>
</ol>
<h2>Novo Cliente</h2>
<br>
<%= render 'form' %>

app/views/clientes/show.html.erb
<br>
<h2> Informações do Cliente: </h2>
<div class="teste">
<p id="notice"><%= notice %></p>

<p >
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @cliente.endereco %>
</p>

<p>
  <strong>Foneresidencial:</strong>
  <%= @cliente.foneResidencial %>
</p>

<p>
  <strong>Fonecelular:</strong>
  <%= @cliente.foneCelular %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @cliente.cpf %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<p>
  <strong>Datanascimento:</strong>
  <%= @cliente.dataNascimento %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @cliente.bairro %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @cliente.cidade %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @cliente.cep %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @cliente.estado %>
</p>
</div>
<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>