config/routes.rb
SisconOtica::Application.routes.draw do

  resources :nomes

  resources :vendas 
  resources :clientes

  resources :tipo_funcionarios

  devise_for :funcionarios,  :controllers => { :registrations => "funcionarios/registrations" }
  resources :tipo_produtos

  resources :produtos
  get '/cadastrar' => 'welcome#cadastrar'
  get '/consultar' => 'welcome#consultar'
  get '/relatorios' => 'welcome#relatorios'
  get '/funcionarios' => 'welcome#listafuncionarios'
  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :authenticate_funcionario!

	def index
	end

	def consultar
	end

	def relatorios
		@vendas = Venda.all
	end

	def cadastrar
	end

	def listafuncionarios

	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/cadastrar.html.erb
<div class="row" style="margin-left: 30px">
<div class="span2">
<%= link_to new_cliente_path do %>
    <div class="novoclientesbutton"></div>
<% end %>
</div>
<div class="span2">
<%= link_to new_produto_path do %>
	<div class="novoprodutosbutton"></div>
<% end %>
</div>
<div class="span2">
<%= link_to new_tipo_produto_path do %>
	<div class="novocategoriasbutton"></div>
<% end %>
</div>
<div class="span2">
<%= link_to new_funcionario_registration_path do %>
	<div class="novofuncionariosbutton"></div>
<% end %>
</div>

app/views/welcome/consultar.html.erb
<div class="row" style="margin-left: 30px">
<div class="span2">
<%= link_to clientes_path do %>
    <div class="clientesbutton"></div>
<% end %>
</div>
<div class="span2">
<%= link_to produtos_path do %>
	<div class="produtosbutton"></div>
<% end %>
</div>
<div class="span2">
<%= link_to tipo_produtos_path do %>
	<div class="categoriasbutton"></div>
<% end %>
</div>
<div class="span2">
<%= link_to funcionarios_path do %>
	<div class="funcionariosbutton"></div>
<% end %>
</div>

app/views/welcome/index.html.erb
<h2> SisconOticas </h2>
<p>
Bem-vindos
</p>

app/views/welcome/relatorios.html.erb
<br>
<h2> Relatorio de Vendas: </h2>

<table width="100%" class="table table-hover table-bordered" style="background: #ffffff">
	<thead style="text-align: left;">
		<tr>
			<th> Codigo </th>
			<th> Funcionario </th>
			<th> Produtos </th>
			<th> Data </th>
			<th> Valor Total </th>
		</tr>
	</thead>
	<tbody>
<% @vendas.each do |v| %>
	<tr >
		<td style="vertical-align: top;"> <%= v.id %> </td>
		<td style="vertical-align: top;"> <%= Funcionario.find(v.funcionario_id).nome %> </td>
		<td> <% VendasProdutos.produtos(v.id).each do |p|%>
				<% produto = Produto.find(p.produto_id) %>
				<%= produto.modelo %> <br>	
			<% end %>
		</td>
		<td style="vertical-align: top;"> <%= v.data %></td>
		<td style="vertical-align: top;"> R$ <%= v.valorTotal %></td>
	</tr>
<% end %>
</tbody>
</table>

<%= link_to vendas_path(:format => "pdf") do %>
	<p class="relatoriogerar">
		Gerar Relatorio
	</p>
<% end %>