config/routes.rb
SisconOtica::Application.routes.draw do

  resources :nomes

  resources :vendas 
  resources :clientes

  resources :tipo_funcionarios

  devise_for :funcionarios,  :controllers => { :registrations => "funcionarios/registrations" }
  resources :tipo_produtos

  resources :produtos
  get '/cadastrar' => 'welcome#cadastrar'
  get '/consultar' => 'welcome#consultar'
  get '/relatorios' => 'welcome#relatorios'
  get '/funcionarios' => 'welcome#listafuncionarios'
  root 'welcome#index'

end

app/models/tipo_produto.rb
class TipoProduto < ActiveRecord::Base
	has_many :produtos
end

app/controllers/tipo_produtos_controller.rb
class TipoProdutosController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_funcionario!
  before_action :set_tipo_produto, only: [:show, :edit, :update, :destroy]

  # GET /tipo_produtos
  # GET /tipo_produtos.json
  def index
    @tipo_produtos = TipoProduto.all
  end

  # GET /tipo_produtos/1
  # GET /tipo_produtos/1.json
  def show
  end

  # GET /tipo_produtos/new
  def new
    @tipo_produto = TipoProduto.new
  end

  # GET /tipo_produtos/1/edit
  def edit
  end

  # POST /tipo_produtos
  # POST /tipo_produtos.json
  def create
    @tipo_produto = TipoProduto.new(tipo_produto_params)

    respond_to do |format|
      if @tipo_produto.save
        format.html { redirect_to @tipo_produto, notice: 'Tipo produto was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tipo_produto }
      else
        format.html { render action: 'new' }
        format.json { render json: @tipo_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_produtos/1
  # PATCH/PUT /tipo_produtos/1.json
  def update
    respond_to do |format|
      if @tipo_produto.update(tipo_produto_params)
        format.html { redirect_to @tipo_produto, notice: 'Tipo produto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tipo_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_produtos/1
  # DELETE /tipo_produtos/1.json
  def destroy
    @tipo_produto.destroy
    respond_to do |format|
      format.html { redirect_to tipo_produtos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_produto
      @tipo_produto = TipoProduto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_produto_params
      params.require(:tipo_produto).permit(:tipo)
    end
end

app/helpers/tipo_produtos_helper.rb
module TipoProdutosHelper
end

app/views/tipo_produtos/_form.html.erb
<%= simple_form_for(@tipo_produto) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :tipo %>
  </div>
    <%= f.button :submit, "Cadastrar tipo_produto", class: "relatoriogerar"%>
<% end %>

app/views/tipo_produtos/edit.html.erb
<h1>Editando Categoria</h1>

<%= render 'form' %>
<br>
<%= link_to 'Voltar', tipo_produtos_path, class: "relatoriogerar"%>

app/views/tipo_produtos/index.html.erb
<h1>Listando Categorias</h1>

<table>
  <thead>
    <tr>
      <th>Categoria</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_produtos.each do |tipo_produto| %>
      <tr>
        <td><%= tipo_produto.tipo %></td>
        <td><%= link_to 'Editar', edit_tipo_produto_path(tipo_produto) %></td>
        <td><%= link_to 'Apagar', tipo_produto, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar Categoria', new_tipo_produto_path, class: "relatoriogerar"%> 

app/views/tipo_produtos/new.html.erb
<br>
<h2>Nova Categoria</h2>
<br>
<%= render 'form' %>

<%= link_to 'Voltar', tipo_produtos_path, class: "relatoriogerar"%>

app/views/tipo_produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @tipo_produto.tipo %>
</p>

<%= link_to 'Edit', edit_tipo_produto_path(@tipo_produto) %> |
<%= link_to 'Back', tipo_produtos_path %>