config/routes.rb
SisconOtica::Application.routes.draw do

  resources :nomes

  resources :vendas 
  resources :clientes

  resources :tipo_funcionarios

  devise_for :funcionarios,  :controllers => { :registrations => "funcionarios/registrations" }
  resources :tipo_produtos

  resources :produtos
  get '/cadastrar' => 'welcome#cadastrar'
  get '/consultar' => 'welcome#consultar'
  get '/relatorios' => 'welcome#relatorios'
  get '/funcionarios' => 'welcome#listafuncionarios'
  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SisconOtica</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<% if funcionario_signed_in? %> 
  <body style="margin-bottom: 0px; background-color: #f4f4f4; background-image: url(<%= asset_path 'fundo.jpg'%>)">
<%else%>
  <body style="margin-bottom: 0px; background-color: #f4f4f4">
<% end %>
<% if funcionario_signed_in? %>
      <%= link_to "Produtos", :produtos %>
<div class="total" >

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
 
          <div class="container nav-collapse">

            <ul class="nav">
            <li>   <%= link_to root_path do %>
          <img src="<%=asset_path 'logop.png'%>" style="height: 25px; margin-left:-20px"/>
          <% end %> </li>
              <li><%= link_to "Inicio", root_path  %></li>
              <li><%= link_to "Segurança", edit_funcionario_registration_path(current_funcionario)  %></li>
              <li><%= link_to "Ajuda", "#"  %></li>
              <li><%= link_to "Sair", destroy_funcionario_session_path, method: 'delete', class: "blog-nav-item pull-right" %>  </li> 

            </ul>
      <% if funcionario_signed_in? %>  
            <%= link_to current_funcionario.email, edit_funcionario_registration_path(current_funcionario), class: "blog-nav-item pull-right", style: "margin-top:10px;" %>
      <% end %>
        <% if current_funcionario.tipo == "Administrador" %>
        <img src="<%=asset_path 'admin.png'%>" class="pull-right" style="margin-top: 4px">
        
        <% else %>
        <img src="<%=asset_path 'vendedor.png'%>" class="pull-right" style="margin-top: 4px">
        <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container" style="margin-top: 23px;margin-bottom: 0px;">
        <div class="row" >
          <div class="span2">
            <div class="sidebar-nav" style="margin-left: -60px; margin-top: 20px;">
              
                <%= link_to cadastrar_path do %>
                	<div class="cadastrarbutton"></div>
                <%end%>
                <%= link_to consultar_path do %>
                	<div class="consultarbutton"></div>
                <%end%>
                <%= link_to relatorios_path do %>
                	<div class="relatoriosbutton"></div>
                <%end%>
                <%= link_to new_venda_path do %>
                	<div class="vendasbutton"></div>
                <%end%>
            </div><!--/.well -->
          </div><!--/span-->
          <div class="span9">
          	<div style="margin-left: 0px;">
            <%= bootstrap_flash %>
            <% if notice != nil || alert != nil %>
            <p class="notice"><%= notice %></p>
      		<p class="alert"><%= alert %></p>
      		<% end %>
            <%= yield %>
            </div>
            </div>

        </div><!--/row-->

    </div> 
    </div>
  <% else %>
  <%= yield %>
  <%end%>
</body>
</html>

app/views/layouts/fluid.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SisconOtica" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

<!-- /container -->

  </body>
</html>